"use server";

import { randomBytes } from "crypto";
import { revalidatePath } from "next/cache";
import { eq, sql } from "drizzle-orm";
import { db } from "@/db";
import { backlogItems, uatTesters } from "@/db/schema";
import { requireAdmin } from "@/lib/admin";
import { getRetestReadiness } from "@/lib/uat-retest";
import { scopeBacklogItems } from "@/lib/backlog/scope";

/**
 * Back-office controls for the tester program: the reviewable backlog and
 * personal tester links. Everything gates on requireAdmin before touching
 * a row, same stance as the account controls next door.
 */

const BACKLOG_STATUSES = ["new", "approved", "rejected", "done"] as const;
export type BacklogStatus = (typeof BACKLOG_STATUSES)[number];

export async function setBacklogStatus(
  id: string,
  status: BacklogStatus
): Promise<void> {
  await requireAdmin();
  if (!BACKLOG_STATUSES.includes(status)) return;
  await db
    .update(backlogItems)
    .set({ status, updatedAt: new Date() })
    .where(eq(backlogItems.id, id));
  revalidatePath("/admin");
  revalidatePath("/admin/testing");
}

/**
 * Retry scoping for one item, waiting for the result. The submit path
 * scopes in the background because a tester is waiting; here the person
 * waiting is the one who pressed the button, and they want the answer.
 */
export async function rescopeBacklogItem(id: string): Promise<void> {
  await requireAdmin();
  await scopeBacklogItems([id]);
  revalidatePath("/admin");
  revalidatePath("/admin/testing");
}

export type CreateTesterResult = { error: string | null };

export async function createUatTester(
  _prev: CreateTesterResult,
  formData: FormData
): Promise<CreateTesterResult> {
  await requireAdmin();
  const name = String(formData.get("name") ?? "").trim().slice(0, 120);
  const email = String(formData.get("email") ?? "").trim().slice(0, 200);
  if (!name) return { error: "The tester needs a name." };
  if (!email.includes("@")) return { error: "That email does not look right." };

  // 8 random bytes base64url: 11 characters, unguessable, short enough to
  // read aloud over the phone if it ever comes to that.
  await db.insert(uatTesters).values({
    token: randomBytes(8).toString("base64url"),
    name,
    email,
  });
  revalidatePath("/admin");
  revalidatePath("/admin/testing");
  return { error: null };
}

/**
 * A link with nobody attached: for communities where the owner has no
 * name or email to enter. The first tester to open it claims it with
 * their own details (see claimUatTester in the uat actions).
 */
export async function createBlankUatTester(): Promise<void> {
  await requireAdmin();
  await db.insert(uatTesters).values({
    token: randomBytes(8).toString("base64url"),
    name: "",
    email: "",
  });
  revalidatePath("/admin");
  revalidatePath("/admin/testing");
}

export async function deleteUatTester(id: string): Promise<void> {
  await requireAdmin();
  // Reports survive: tester_id is ON DELETE SET NULL, so their submitted
  // runs stay in the archive under the name they typed.
  await db.delete(uatTesters).where(eq(uatTesters.id, id));
  revalidatePath("/admin");
  revalidatePath("/admin/testing");
}

/**
 * Send a tester back for a second look.
 *
 * Sets their focus to exactly the checks whose bugs have been fixed since
 * they last ran, bumps the round so the browser draft starts clean, and
 * stamps retest_at so those checks cannot come round again.
 *
 * Deliberately a button rather than something automatic. The generated
 * list is correct by construction, but whether tonight is the night to ask
 * somebody for another hour of their time is a judgement, not a query.
 */
export async function generateRetest(testerId: string): Promise<void> {
  await requireAdmin();

  const ready = (await getRetestReadiness()).get(testerId);
  if (!ready || ready.checkIds.length === 0) return;

  await db
    .update(uatTesters)
    .set({
      focus: ready.checkIds,
      round: sql`${uatTesters.round} + 1`,
      retestAt: new Date(),
      // Their old answers belong to the previous run. Clearing the draft
      // stops round one's write-ups resurfacing under round two's checks.
      draft: null,
      draftUpdatedAt: null,
    })
    .where(eq(uatTesters.id, testerId));

  revalidatePath("/admin");
  revalidatePath("/admin/testing");
}

/**
 * Put a tester back on the full punch list.
 *
 * The way out of a retest, for when somebody should start over or a focus
 * list was generated by mistake.
 */
export async function clearRetest(testerId: string): Promise<void> {
  await requireAdmin();
  await db
    .update(uatTesters)
    .set({ focus: null, draft: null, draftUpdatedAt: null })
    .where(eq(uatTesters.id, testerId));
  revalidatePath("/admin");
  revalidatePath("/admin/testing");
}
